import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Questions from "../public/questions.json";
import Link from "next/link";

export default function Home() {
  console.log(Questions);

  return (
    <>
      <Head>
        <title>Kahevõitlus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Kahevõitlus</h1>
        <h2>Vali küsimus</h2>
        {Questions.questions.map((question) => (
          <Link className={styles.question} key={question.question} href={`/${question.question}`}>
            {question.question}
          </Link>
        ))}
      </main>
    </>
  );
}
