import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Questions from "../public/questions.json";
import Link from "next/link";

import { useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  // console.log(Questions);
  const [theme, setTheme] = useState("default");
  const router = useRouter();

  useEffect(() => {
    if (router.isReady) {
      const queryTheme = router.query.theme;
      setTheme(queryTheme || "default");
    }
  }, [router.isReady]);

  const resetGame = () => {
    router.push("/");
    setTheme("default");
  }

  return (
    <>
      <Head>
        <title>Kahevõitlus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${theme === "KOIT" ? styles.koitBg : ""}`}>
        <h1>Kahevõitlus</h1>
        <div className={styles.toggleContainer}>
          <span className={styles.toggleContainerTitle}>Teema:</span>
          Tavaline
          <label className={styles.toggle}>
            <input
              className={styles.toggleInput}
              type="checkbox"
              onChange={() => {
                const newTheme = theme === "KOIT" ? "default" : "KOIT";
                setTheme(newTheme);
                router.push({ query: { ...router.query, theme: newTheme } });
              }}
              checked={theme === "KOIT"}
            />
            <span className={styles.slider}></span>
          </label>
          KOIT
        </div>
        <div className={styles.topContainer}>
          <h2>Vali küsimus</h2>
          <button onClick={resetGame} className={styles.resetDataButton}>Lähtesta andmed</button>
        </div>
        <div className={styles.questions}>
          {Questions.questions.map((question) => (
            <Link className={styles.question} key={question.question} href={{ pathname: `/${encodeURIComponent(question.question)}`, query: { ...router.query, p1s: router.query.p1s ? router.query.p1s : Number(0), p2s: router.query.p2s ? router.query.p2s : Number(0) } }}>
              {question.question}
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
